# Generated by Django 4.1.4 on 2023-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ads_Name', models.CharField(max_length=1000)),
                ('Ads_HTML', models.TextField()),
                ('Visibility', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('Card', 'Card ads'), ('sheet', 'Tips ads'), ('Image', 'Images ads'), ('Search', 'Url/flat cards')], default='Card', max_length=100)),
                ('Shifted', models.CharField(max_length=1000)),
                ('Position_Number', models.IntegerField()),
            ],
        ),
    ]
