# Generated by Django 4.1.4 on 2023-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Status',
            field=models.CharField(choices=[('Edit', 'Edit'), ('Create', 'Create')], default='create', max_length=100),
            preserve_default=False,
        ),
    ]
