# Generated by Django 4.1.4 on 2023-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='Status',
            field=models.CharField(choices=[('Edit', 'Edit'), ('Create', 'Create'), ('Others', 'Others')], default='Create', max_length=100),
        ),
    ]
