# Generated by Django 3.2.3 on 2022-06-03 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='another',
            name='another',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
