# Generated by Django 3.2.3 on 2022-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(choices=[('choose', 'choose what you want to send us'), ('message', 'Message'), ('questions', 'Questions'), ('issues', 'Issues'), ('suggestions for creating tips', 'Suggestions for creating tips'), ('suggestions for improving our tips', 'Suggestions for improving tips')], default='choose', max_length=100),
        ),
    ]
