# Generated by Django 3.2.3 on 2022-05-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='color',
            new_name='contact_type',
        ),
    ]
