# Generated by Django 3.2.3 on 2022-05-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_color_contact_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='User_profile',
        ),
    ]
