# Generated by Django 3.2.3 on 2022-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_contact_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credited_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Default.jpg', null=True, upload_to='static/users/')),
                ('contact_No', models.IntegerField()),
            ],
        ),
    ]
